apiVersion: v1
kind: Service
metadata:
  name: python-cicd-service
  namespace: python-cicd
spec:
  selector:
    app: python-cicd-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP